apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-secret-volume
  name: helloworld-secret-volume
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: helloworld-secret-volume
    ports:
    - containerPort: 8080
    resources: {}
    volumeMounts:
      # Volume名を指定
    - name: my-secret-volume
      # Volumeをマウントするコンテナ内のファイルパスを指定
      mountPath: /my-secret
      readOnly: true
  volumes:
    # 作成するVolume名を指定
    - name: my-secret-volume
      secret:
        # Secret名を指定
        secretName: my-secret
status: {}
